# Generated by Django 4.1.4 on 2022-12-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_movie_created_at_alter_movie_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender'), ('Rather Not to Say', 'Rather Not to Say')], max_length=150)),
                ('dob', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
