# Generated by Django 4.1.4 on 2022-12-26 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_cast'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.movie'),
        ),
    ]
